const GOOGLEBOOKS_API_KEY = 'AIzaSyAqGn7oUYS5vvxuRVPvuTSMvVzBRJBWDuk';

const OPENAI_API_KEY = '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';

module.exports = {
    GOOGLEBOOKS_API_KEY: GOOGLEBOOKS_API_KEY,
    OPENAI_API_KEY: OPENAI_API_KEY
}